package com.ruoqian.brainidphoto.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "idphoto_print".
*/
public class IdphotoPrintDao extends AbstractDao<IdphotoPrint, Long> {

    public static final String TABLENAME = "idphoto_print";

    /**
     * Properties of entity IdphotoPrint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property PNum = new Property(1, Integer.class, "pNum", false, "pNum");
        public final static Property PPrice = new Property(2, float.class, "pPrice", false, "pPrice");
        public final static Property CreateTime = new Property(3, Long.class, "createTime", false, "createTime");
        public final static Property CloudUpdateTime = new Property(4, Long.class, "cloudUpdateTime", false, "cloudUpdateTime");
        public final static Property CloudId = new Property(5, Long.class, "cloudId", false, "cloudId");
    }


    public IdphotoPrintDao(DaoConfig config) {
        super(config);
    }
    
    public IdphotoPrintDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"idphoto_print\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"pNum\" INTEGER," + // 1: pNum
                "\"pPrice\" REAL NOT NULL ," + // 2: pPrice
                "\"createTime\" INTEGER," + // 3: createTime
                "\"cloudUpdateTime\" INTEGER," + // 4: cloudUpdateTime
                "\"cloudId\" INTEGER);"); // 5: cloudId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_idphoto_print_cloudId ON \"idphoto_print\"" +
                " (\"cloudId\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"idphoto_print\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IdphotoPrint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer pNum = entity.getPNum();
        if (pNum != null) {
            stmt.bindLong(2, pNum);
        }
        stmt.bindDouble(3, entity.getPPrice());
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(4, createTime);
        }
 
        Long cloudUpdateTime = entity.getCloudUpdateTime();
        if (cloudUpdateTime != null) {
            stmt.bindLong(5, cloudUpdateTime);
        }
 
        Long cloudId = entity.getCloudId();
        if (cloudId != null) {
            stmt.bindLong(6, cloudId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IdphotoPrint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer pNum = entity.getPNum();
        if (pNum != null) {
            stmt.bindLong(2, pNum);
        }
        stmt.bindDouble(3, entity.getPPrice());
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(4, createTime);
        }
 
        Long cloudUpdateTime = entity.getCloudUpdateTime();
        if (cloudUpdateTime != null) {
            stmt.bindLong(5, cloudUpdateTime);
        }
 
        Long cloudId = entity.getCloudId();
        if (cloudId != null) {
            stmt.bindLong(6, cloudId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IdphotoPrint readEntity(Cursor cursor, int offset) {
        IdphotoPrint entity = new IdphotoPrint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // pNum
            cursor.getFloat(offset + 2), // pPrice
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // createTime
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // cloudUpdateTime
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // cloudId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IdphotoPrint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPNum(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPPrice(cursor.getFloat(offset + 2));
        entity.setCreateTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setCloudUpdateTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setCloudId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IdphotoPrint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IdphotoPrint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IdphotoPrint entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
